services:
  # -------------------------------------------------------------
  # 1. Laravel Web Application Service (Docker)
  # -------------------------------------------------------------
  - type: web
    name: ecommerce-platform
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: LuxeCart
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: FILESYSTEM_DISK
        value: supabase
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
